name: Continuous Deployment
on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Dcoker build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: arvindkhoisnam/go-server:${{ github.sha }}
          # build-args: |
          #   DATABASE_URL=${{ secrets.DATABASE_URL }}

      # - name: Deploy to VM
      #   uses: appleboy/ssh-action@master
      #   with:
      #     host: ${{ secrets.VM_HOST }}
      #     username: root
      #     key: ${{ secrets.VM_SSH_KEY }}
      #     port: 22
      #     script: |
      #       docker pull arvindkhoisnam/go-server:${{ github.sha }}
      #       docker stop go-server || true
      #       docker rm go-server || true
      #       docker run -d --name go-server -p 8080:8080 arvindkhoisnam/go-server:${{ github.sha }}
